
version: 0.2

phases:
  install:
    commands:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - docker build --tag "388925426397.dkr.ecr.ap-southeast-1.amazonaws.com/notejam-flask:latest" .      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push "388925426397.dkr.ecr.ap-southeast-1.amazonaws.com/notejam-flask:latest"
